server:
  ssl:
    key-store: classpath:https_keystore.p12
    key-store-password: chujian
    keyStoreType: PKCS12
    keyAlias: 1
  port: 8443
  http-port: 8080
  servlet:
    application-display-name: firstmeet-mservice-paycenter-meizu
    contextPath: /
  tomcat:
    basedir: "./"
    accesslog:
      enabled: true
      directory: ${FIRSTMEET_MSERVICE_DATA_BASEDIR:.}/logs/${HOSTNAME:1}/access-log
    customized.enable: true
    customized.accept-count: 100
    customized.max-threads: 200
    customized.min-spare-threads: 25
    customized.max-connections: 10000
    customized.connection-timeout: 2000
    manager.enable: false
    manager.context-path: '/data/webapps/manager'

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://192.168.1.220:3306/pay_center_meizu?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: kaifa
    password: '{cipher}AQAIqUu64z0+2z3AVgEgIWqeBE51aP4vVNHaxShTvz6gIcSoB5nX2jc3aVtcRHi5IY4ykzDA8jZ3893YbR/d7OIU/WvFlml9PdwJXIi4TC6HBZyrEbEQVMm9g4e6axGO/uY46R7TEkn8rM8wkc6CmdOemF4ekK3brPBcwnYJhoNJI9UlQ4ayg9zMYVFOVG28NSq84htRKgJSLolATtdaEJPl/LpveVvByMk3hcVXBVHYz+FzyxCgZnWMM6kU25qx9vbzvr3ChBplZBaPvtamuoZr5GOTaNeYTIOs6/6pFsRlB7PkD5fbQNKpBwENv5TyKt+JXMfPiy4zWYjszGBUQs2+RQSdDD5gIyrf6KFHNXsg8dx1XOUCE5JFtDiKUNDmuFI='
    druid:
      initial-size: 50
      min-idle: 50
      max-active: 600
      max-wait: 2000  #配置获取连接等待超时的时间
      time-between-eviction-runs-millis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000 #配置一个连接在池中最小生存的时间，单位是毫秒
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filters: stat,slf4j
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  jackson:
    serialization:
      indent_output: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

meizupay:
  payment:
    query.url: https://api.game.meizu.com/game/order/query

chujian:
   drools:
     rule:
       path: 'classpath*:rules/**/client-config-dev.xls' #Can configure absolute path: file:/data/rules/**/*.drl

uid.grpc:
  host: 'uidgenerator.ups.firstmeet'
  port: 6565


